# Generated by Django 5.2.8 on 2025-11-09 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitrecord",
            name="date",
        ),
        migrations.AddField(
            model_name="habitrecord",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
